apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: ctfd-cache-claim0
  name: ctfd-cache-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
