---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ctfd
  namespace: flux-system
spec:
  interval: 30m
  releaseName: ctfd
  chartRef:
    kind: OCIRepository
    name: ctfd
  targetNamespace: ctfd
  values:
    replicaCount: 1
    image:
      repository: ctfd/ctfd
      tag: 3.5.0
      pullPolicy: IfNotPresent
    redis:
      enabled: True
      auth:
        enabled: true
      architecture: standalone

    mariadb:
      enabled: false
      galera:
        name: ctfd
        mariabackup:
          user: "mariabackup"
          password: "CTFd2025!"
      persistence:
        enabled: false
        storageClass: ""
        accessModes:
          - ReadWriteOnce
        size: 15Gi

    env:
      open:
        SECRET_KEY: "fArwMLj4011BRZJT9sRJpgmxQFm1zsR6"
        WORKERS: 5
        REVERSE_PROXY: True
      existingSecret: "ctfd-creds"
      existingSecretMappings:
        DATABASE_URL: "DATABASE_URL"
        REDIS_PASSWORD: "REDIS_PASSWORD"

    persistence:
      uploads:
        enabled: true
        storageClass: local-path
        accessMode: ReadWriteOnce
        size: 10Gi
    service:
      type: ClusterIP
      port: 80
      targetPort: 8000
    probes:
      liveness:
        initialDelaySeconds: 15
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
      readiness:
        initialDelaySeconds: 15
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
    ingress:
      class: tailscale
      enabled: true
      annotations:
        tailscale.com/funnel: "true"
      hosts:
        - host: ctfd
          path: "/"
      tls:
        - secretName: ctfd-tls
          hosts:
            - ctfd
    resources:
      limits:
        cpu: 500m
        memory: 700Mi
      requests:
        cpu: 300m
        memory: 300Mi
    metrics:
      enabled: true
      image:
        registry: docker.io
        repository: bitnami/mysqld-exporter
        tag: 0.12.1-debian-10-r27
        pullPolicy: IfNotPresent
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9104"

      serviceMonitor:
        enabled: true
        namespace: monitoring
        interval: 10s
        scrapeTimeout: 10s
        selector:
          prometheus: kube-prometheus
