---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: ctfd
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://ghcr.io/bman46/ctfd/ctfd
  ref:
    semver: "0.2.0"
---
