apiVersion: v1
kind: Namespace
metadata:
  name: wallabag
  labels:
    name: wallabag
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wallabag-dev-cluster
  namespace: wallabag
spec:
  instances: 2

  storage:
    size: 8Gi
