---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    pod-security.kubernetes.io/enforce = "privileged"
    app = "external-secrets"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  interval: 1m0s
  releaseName: external-secrets
  targetNamespace: kube-system
  values:
    certController:
      create: true
      replicaCount: 1
      requeueInterval: 5m
      revisionHistoryLimit: 5
    concurrent: 1
    crds:
      conversion:
        enabled: true
      createClusterExternalSecret: true
      createClusterSecretStore: true
      createPushSecret: true
    createOperator: true
    dnsPolicy: ClusterFirst
    installCRDs: true
    log:
      level: info
      timeEncoding: epoch
    processClusterExternalSecret: true
    processClusterStore: true
    processPushSecret: true
    replicaCount: 1
    revisionHistoryLimit: 4
