---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  chart:
    spec:
      chart: vaultwarden
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
        namespace: flux-system
      version: 7.8.2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  interval: 10m
  releaseName: argo
  targetNamespace: vaultwarden
  values:
    
