apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: security-staging
  namespace: flux-system
spec:
  dependsOn:
    - name: secrets
  interval: 15m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./security/staging
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
