---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: pihole-pv-prod
  namespace: networking
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
    - mfsymlinks
    - nobrl
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: pihole
    volumeAttributes:
      source: //10.3.3.11/Home-Share/prod/pihole
    nodeStageSecretRef:
      name: smbcreds-pihole
      namespace: networking
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-pihole-prod
  namespace: networking
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pihole-pv-prod
  storageClassName: smb
