apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wallabag-prod-redis-creds
  namespace: wallabag
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: wallabag-prod-redis-creds
  data:
  - secretKey: password
    remoteRef:
      key: wallabag_prod
      property: redis_password
