---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: storage
        namespace: flux-system
      version: 1.7.1
  interval: 1m0s
  releaseName: longhorn
  targetNamespace: longhorn-system
