---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 10m0s
  provider: generic
  ref:
    tag: 8.7.7
  url: oci://registry-1.docker.io/bitnamicharts/external-dns
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: external-dns
    namespace: flux-system
  install:
    crds: Create
  interval: 1m0s
  targetNamespace: pihole-system
  upgrade:
    crds: CreateReplace
  values:
    extraEnvVars:
    - name: EXTERNAL_DNS_PIHOLE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: pihole-password
    ingressClassFilters:
    - cilium
    pihole:
      server: http://pihole-web.pihole-system.svc.cluster.local
    policy: upsert-only
    provider: pihole
    serviceAccount:
      create: true
      name: external-dns
    txtOwnerId: homelab
