---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: operator
  namespace: flux-system
spec:
  
  chartRef:
    kind: OCIRepository
    name: operator
    namespace: flux-system
  install:
    crds: Create
  interval: 1m0s
  targetNamespace: security
  upgrade:
    crds: CreateReplace
  values:
    image:
      tag: 4.13.0
    metrics:
      serviceMonitor:
        enabled: true
    minio:
      enabled: false
    s3:
      enabled: true
      endpoint: "s3.us-east-1.amazonaws.com"
      bucket: "dev-securecodebox-backup-956f9b7c-d877-0874-a379-f4361114dfac"
      keySecret: securecodebox-s3-staging
    resources:
      limits:
        cpu: 120m
        memory: 70Mi
      requests:
        cpu: 120m
        memory: 40Mi
