apiVersion: v1
kind: Namespace
metadata:
  name: vaultwarden
  labels:
    name: vaultwarden
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-cluster
  namespace: vaultwarden
spec:
  instances: 2
  storage:
    storageClass: smb
    size: 10Gi
  walStorage:
    size: 2Gi
