apiVersion: v1
kind: Namespace
metadata:
  name: vaultwarden
  labels:
    name: vaultwarden
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-cluster
  namespace: vaultwarden
spec:
  postgresql:
    pg_hba:
      - hostssl postgres vaultwarden 10.43.0.0/16 scram-sha-256
  instances: 3
  storage:
    storageClass: local-path
    size: 10Gi
  walStorage:
    size: 2Gi
