---
apiVersion: v1
kind: Namespace
metadata:
  name: db-ops
  labels:
    app: "database_operations"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: db-ops
spec:
  interval: 24h
  url: https://cloudnative-pg.github.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: db-ops
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.23.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: db-ops
      interval: 12h
