apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wallabag-dev-redis-creds
  namespace: redis
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: wallabag-dev-redis-creds
  data:
  - secretKey: password
    remoteRef:
      key: wallabag_dev
      property: redis_password
