---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wallabag-dev-cluster
  namespace: wallabag
spec:
  postgresql:
    pg_hba:
      - hostssl postgres wallabag 10.43.0.0/16 scram-sha-256
  instances: 3
  storage:
    size: 10Gi
    storageClass: longhorn
  walStorage:
    size: 2Gi
  bootstrap:
    recovery:
      source: wallabag-dev-cluster
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: wallabag-dev-cluster-backup
  externalClusters:
  - name: wallabag-dev-cluster
    plugin:
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: wallabag-dev-cluster
        serverName: wallabag-dev-cluster
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: wallabag-backup
  namespace: wallabag
spec:
  schedule: "0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: wallabag-dev-cluster
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io

