---
apiVersion: v1
kind: Namespace
metadata:
  name: wallabag
  labels:
    app = "wallabag"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wallabag-dev-cluster
  namespace: wallabag
spec:
  postgresql:
    pg_hba:
      - hostssl postgres wallabag 10.43.0.0/16 scram-sha-256
  instances: 2
  storage:
    storageClass: smb
    size: 10Gi
  walStorage:
    size: 2Gi

