---
apiVersion: v1
kind: Namespace
metadata:
  name: wallabag
  labels:
    app = "wallabag"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wallabag-dev-cluster
  namespace: wallabag
spec:
  postgresql:
    pg_hba:
      - hostssl postgres wallabag 10.43.0.0/16 scram-sha-256
  instances: 3
  storage:
    size: 10Gi
    storageClass: smb
    pvcTemplate:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 10Gi
      volumeMode: Filesystem
  walStorage:
    size: 2Gi

