---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wallabag-dev-redis-cluster
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: redis-cluster
      version: "0.17.0"
      sourceRef:
        kind: HelmRepository
        name: ot-helm
        namespace: flux-system
      interval: 6h
  targetNamespace: redis
  values:
    redisCluster:
      name: "wallabag-dev-redis-cluster"
      clusterSize: 3
      clusterVersion: v7
      persistenceEnabled: true
      image: quay.io/opstree/redis
      tag: v7.0.15
      imagePullPolicy: IfNotPresent
      redisSecret:
        secretName: "wallabag-dev-redis-creds"
        secretKey: "password"
      leader:
        replicas: 3
        serviceType: ClusterIP
        nodeSelector:
          node: "worker"
      follower:
        replicas: 3
        serviceType: ClusterIP
        nodeSelector:
          node: "worker"
    labels:
      app: "wallabag"

    externalConfig:
      enabled: false
      data: |
        slowlog-max-len 158
        stream-node-max-bytes 2048
        tcp-keepalive 0
        maxmemory 1024mb
        timeout 300

    externalService:
      enabled: false
      serviceType: LoadBalancer
      port: 6379

    serviceMonitor:
      enabled: true
      interval: 30s
      scrapeTimeout: 10s
      namespace: monitoring

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
      nodeConfVolume: true
      nodeConfVolumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
