---
apiVersion: v1
kind: Namespace
metadata:
  name: wallabag
  labels:
    app = "wallabag"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wallabag-dev-cluster
  namespace: wallabag
spec:
  postgresql:
    pg_hba:
      - hostssl postgres wallabag 10.43.0.0/16 scram-sha-256
  instances: 3
  storage:
    size: 10Gi
    storageClass: local-path
  walStorage:
    size: 2Gi
  backup:
    barmanObjectStore:
      destinationPath: s3://BUCKET_NAME/path/to/folder
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
    retentionPolicy: "15d"
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: wallabag-backup
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: wallabag-dev-cluster

