---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homelab-blog
  namespace: flux-system
spec:
  chart:
    spec:
      chart: homelab
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: homelab-blog
        namespace: flux-system
      version: 1.0.0
  interval: 1m0s
  releaseName: homelab-blog
  targetNamespace: homelab
  values:
    image:
      pullPolicy: IfNotPresent
      repository: fonalex45/homelab
      tag: v2.6.0
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
        nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
      className: cilium
      enabled: true
      hosts:
      - host: dev.internal.homelab.fr3d.dev
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - dev.internal.homelab.fr3d.dev
        secretName: dev-homelab-tls
    livenessProbe:
      httpGet:
        path: /
        port: http
    readinessProbe:
      httpGet:
        path: /
        port: http
    replicaCount: 1
    service:
      port: 80
      type: ClusterIP
    serviceAccount:
      automount: true
      create: true
      name: ""
    volumeMounts: []
    volumes: []
