apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      version: 1.15.3
  interval: 1m0s
  retryInterval: 1m0s
  prune: true
  releaseName: cert-manager
  targetNamespace: cert-manager
  values:
    clusterResourceNamespace: cert-manager
    crds:
      enabled: true
      keep: true
    disableAutoApproval: false
    dns01RecursiveNameservers: 1.1.1.1:53,8.8.8.8:53
    enableCertificateOwnerRef: true
    global:
      leaderElection:
        namespace: cert-manager
      logLevel: 3
      rbac:
        aggregateClusterRoles: true
        create: true
    image:
      pullPolicy: IfNotPresent
      repository: quay.io/jetstack/cert-manager-controller
    maxConcurrentChallenges: 60
    namespace: cert-manager
    replicaCount: 1
    webhook:
      replicaCount: 1
      timeoutSeconds: 30
