---
apiVersion: v1
kind: Namespace
metadata:
  name: security
--- 
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubescape
  namespace: flux-system
spec:
  interval: 1h
  url: https://kubescape.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubescape
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kubescape-operator
      sourceRef:
        kind: HelmRepository
        name: kubescape
      version: v1.26.0
  interval: 1h
  targetNamespace: security
  values:
    ksNamespace: security
    ksLabel: security
    capabilities:
      # ====== configuration scanning related capabilities ======
      #
      # Default configuration scanning setup
      configurationScan: enable
      # Continuous Scanning continuously evaluates the security posture of your cluster.
      continuousScan: disable
      nodeScan: enable

      # ====== Image vulnerabilities scanning related capabilities ======
      #
      vulnerabilityScan: enable
      relevancy: enable
      # Generate VEX documents alongside the image vulnerabilities report (experimental)
      vexGeneration: disable

      # ====== Runtime related capabilities ======
      #
      runtimeObservability: enable
      networkPolicyService: enable
      runtimeDetection: disable
      malwareDetection: enable
      nodeProfileService: disable
      seccompProfileService: enable

      # ====== Other capabilities ======
      #
      # This is an experimental capability with an elevated security risk. Read the
      # matching docs before enabling.
      autoUpgrading: disable
      prometheusExporter: enable
      # seccompGenerator: disable

    #extra capability - service discovery option
    serviceScanConfig:
      enabled : false
      interval: 1h
    configurations:
      persistence: enable
      prometheusAnnotations: enable
    persistence:
      storageClass: "local-path"
      accessMode: ReadWriteOnce
      size:
        backingStorage: 5Gi
        kubevuln: 2Gi

