---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    pod-security.kubernetes.io/enforce: "privileged"
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: privileged
    app: "kubescape"
--- 
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubescape
  namespace: flux-system
spec:
  interval: 1h
  url: https://kubescape.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubescape
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kubescape-operator
      sourceRef:
        kind: HelmRepository
        name: kubescape
      version: v1.26.0
  interval: 1h
  targetNamespace: security
  values:
    kubescape:
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 250m
          memory: 200Mi
    kubevuln:
       resources:
         requests:
           cpu: 300m
           memory: 300Mi
      # Consider to increase ephemeral-storage requests in order to avoid pod eviction due to huge images
      # More details: https://hub.armosec.io/docs/limitations
      #               https://github.com/kubescape/kubescape/issues/389
           ephemeral-storage: 5Gi
         limits:
            cpu: 500m
            memory: 1000Mi
            ephemeral-storage: 10Gi
    nodeAgent:
      resources:
        requests:
          cpu: 100m
          memory: 200mi
        limits:
          cpu: 500m
          memory: 1000mi
    ksNamespace: security
    ksLabel: security
    capabilities:
      # ====== configuration scanning related capabilities ======
      #
      # Default configuration scanning setup
      configurationScan: enable
      # Continuous Scanning continuously evaluates the security posture of your cluster.
      continuousScan: disable
      nodeScan: enable

      # ====== Image vulnerabilities scanning related capabilities ======
      #
      vulnerabilityScan: enable
      relevancy: enable
      # Generate VEX documents alongside the image vulnerabilities report (experimental)
      vexGeneration: disable

      # ====== Runtime related capabilities ======
      #
      runtimeObservability: enable
      networkPolicyService: enable
      runtimeDetection: disable
      malwareDetection: disable
      nodeProfileService: disable
      seccompProfileService: enable

      # ====== Other capabilities ======
      #
      # This is an experimental capability with an elevated security risk. Read the
      # matching docs before enabling.
      autoUpgrading: disable
      prometheusExporter: enable
      # seccompGenerator: disable

    #extra capability - service discovery option
    serviceScanConfig:
      enabled : false
      interval: 1h
    configurations:
      persistence: enable
      prometheusAnnotations: enable
    persistence:
      storageClass: "local-path"
      accessMode: ReadWriteOnce
      size:
        backingStorage: 5Gi
        kubevuln: 2Gi

