apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
spec:
  chart:
    spec:
      version: "2.27.0"
  values:
    ingress:
      annotations:
        #cert-manager.io/cluster-issuer: letsencrypt-production
      enabled: true
      hosts:
      - prod-pihole
      ingressClassName: tailscale
      path: /
      pathType: Prefix
      tls:
      - hosts:
        - prod-pihole
        secretName: pihole-tls
    persistentVolumeClaim:
      enabled: true
      storageClass: smb
      existingClaim: pvc-pihole-prod
      accessModes:
        - ReadWriteMany
      size: 50Gi
    serviceDns:
      externalTrafficPolicy: Cluster
      mixedService: true
      LoadBalancerIP: 10.3.3.40
      annotations:
        "lbipam.cilium.io/ips": "10.3.3.40"
      type: LoadBalancer
    podDnsConfig:
      enabled: false
      policy: "None"
      nameservers:
        - 127.0.0.1
        - 8.8.8.8
    resources:
      limits:
        cpu: 400m
        memory: 150Mi
      requests:
        cpu: 400m
        memory: 150Mi
    nodeSelector:
      node: "worker"
    #privileged: "true"
