apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
spec:
  chart:
    spec:
      version: "2.26.2"
  values:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      enabled: true
      hosts:
      - prod-pihole
      ingressClassName: tailscale
      path: /
      pathType: Prefix
      tls:
      - hosts:
        - prod-pihole
        secretName: pihole-tls
    persistentVolumeClaim:
      enabled: true
      storageClass: local-path
      accessModes:
        - ReadWriteOnce
      size: 8092Mi
    serviceDns:
      externalTrafficPolicy: Cluster
      mixedService: true
      LoadBalancerIP: 10.3.3.40
      annotations:
        "lbipam.cilium.io/ips": "10.3.3.40"
      type: LoadBalancer
    podDnsConfig:
      enabled: true
      policy: "None"
      nameservers:
        - 127.0.0.1
        - 8.8.8.8
    resources:
      limits:
        cpu: 400m
        memory: 200Mi
      requests:
        cpu: 400m
        memory: 200Mi
