apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prod-blog
  namespace: flux-system
spec:
  chart:
    spec:
      chart: musings
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: musings
        namespace: flux-system
      version: 0.3.0
  install:
    remediation:
      retries: 3
  interval: 1m0s
  releaseName: prod-blog
  targetNamespace: blog
  upgrade:
    crds: CreateReplace
  values:
    replicaCount: 1
    image:
      repository: fonalex45/blog
      pullPolicy: Always
      tag: "latest"
    serviceAccount:
      create: true
      automount: true
      name: ""
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true
      className: "tailscale"
      annotations:
        #cert-manager.io/cluster-issuer: "letsencrypt-staging"
      hosts:
        - host: prod-blog
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: prod-blog-tls
          hosts:
            - prod-blog
