apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
spec:
  chart:
    spec:
      version: "2.27.0"
  values:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
      enabled: true
      hosts:
      - dev.int.pihole.fr3d.dev
      ingressClassName: cilium
      path: /
      pathType: Prefix
      tls:
      - hosts:
        - dev.int.pihole.fr3d.dev
        secretName: pihole-dev-tls
    persistentVolumeClaim:
      enabled: true
      existingClaim: pvc-pihole-2
      storageClass: smb
      accessModes:
        - ReadWriteMany
      size: 2048Mi
    mixedService: true
