---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: pihole-pv-2
  namespace: networking
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: pihole
    volumeAttributes:
      source: //10.3.3.11/Home-Share
    nodeStageSecretRef:
      name: smbcreds
      namespace: storage
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-pihole-2
  namespace: networking
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pihole-pv-2
  storageClassName: smb
