apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wallabag-prod-creds
  namespace: wallabag
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: wallabag_prod/username
    - secretKey: password
      remoteRef:
        key: wallabag_prod
    - secretKey: app_secret
      remoteRef:
        key: wallabag_prod
    - secretKey: redis_password
      remoteRef:
        key: wallabag_prod
    - secretKey: redis_host
      remoteRef:
        key: wallabag_prod
    - secretKey: database
      remoteRef:
        key: wallabag_prod
    - secretKey: server
      remoteRef:
        key: wallabag_prod
    - secretKey: port
      remoteRef:
        key: wallabag_prod
