---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wallabag-configmap
  namespace: wallabag
data:
  PHP_MEMORY_LIMIT: 500M
  POPULATE_DATABASE: "true"
  SYMFONY__ENV__FOSUSER_REGISTRATION: "false"
  SYMFONY__ENV__DATABASE_DRIVER: pdo_pgsql
  SYMFONY__ENV__DATABASE_HOST: wallabag-dev-cluster-rw
  SYMFONY__ENV__DATABASE_NAME: app
  SYMFONY__ENV__DATABASE_USER: "app"
  SYMFONY__ENV__DATABASE_PASSWORD: "changeme"
  SYMFONY__ENV__DATABASE_PORT: "5432"
  SYMFONY__ENV__DOMAIN_NAME: https://url:443
