apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wallabag-prod-creds
  namespace: wallabag
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  itemPath: "vaults/HomeLab/wallabag_prod"
  
