apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wallabag-external-secret
  namespace: wallabag
spec:
  refreshInterval: 1h
  kind: SecretStore
target:
  name: wallabag-container-env
  creationPolicy: Owner
data:
  - secretKey: SYMFONY__ENV__DATABASE_PASSWORD
    remoteRef:
      key: /K8s/app/dev/Wallabag/wallabag-credentials
      property: SYMFONY__ENV__DATABASE_PASSWORD

  - secretKey: SYMFONY__ENV__DATABASE_USER
    remoteRef:
      key: /K8s/app/dev/Wallabag/wallabag-credentials
      property: SYMFONY__ENV__DATABASE_USER
