apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wallabag-external-secret
  namespace: external-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: parameterstore            # Replace with your actual SecretStore name
    kind: SecretStore                   # or ClusterSecretStore if used cluster-wide
  target:
    name: wallabag-container-env
    creationPolicy: Owner
  data:
    - secretKey: SYMFONY__ENV__DATABASE_PASSWORD
      remoteRef:
        key: /K8s/app/dev/Wallabag/SYMFONY__ENV__DATABASE_PASSWORD
        metadataPolicy: Fetch
    - secretKey: SYMFONY__ENV__DATABASE_USER
      remoteRef:
        key: /K8s/app/dev/Wallabag/SYMFONY__ENV__DATABASE_USER
        metadataPolicy: Fetch

