apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wallabag
  namespace: wallabag
  labels:
    app.kubernetes.io/name: wallabag
  annotations:
    gethomepage.dev/description: Links for Later
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Apps
    gethomepage.dev/icon: wallabag.png
    gethomepage.dev/name: wallabag
    #cert-manager.io/cluster-issuer: letsencrypt-staging

spec:
  ingressClassName: tailscale
  rules:
    - host: "dev-int-wallabag"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: wallabag
                port:
                  number: 80
            tls:
              - hosts:
                  - dev-int-wallabag
