apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-cd
resources:
  - ../../../apps/base/argo-cd/release.yaml
patches:
  - path: patch.yaml
    target:
      kind: HelmRelease
