---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://gissilabs.github.io/charts/

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  chart:
    spec:
      chart: vaultwarden
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
        namespace: flux-system
      version: 1.2.5
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  interval: 10m
  releaseName: argo
  targetNamespace: vaultwarden
  values:
    database:
  # Database type, must be one of: 'sqlite', 'mysql' or 'postgresql'.
      type: postgresql
      url: ""
      existingSecret: vaultwarden-pg
      #existingSecretKey: database-url
      maxConnections: 15
    vaultwarden:
      ## Set Bitwarden URL, mandatory for invitations over email. Recommended if using a reverse proxy / ingress. Format is https://name or http://name
      domain: "https://prod-vw.fr3d.dev"
      # Allow any user to sign-up: https://github.com/dani-garcia/vaultwarden/wiki/Disable-registration-of-new-users
      allowSignups: true
      # Verify e-mail before login is enabled. SMTP must be enabled.
      verifySignup: true
      # When a user logs in an email is required to be sent. If sending the email fails the login attempt will fail. SMTP must be enabled.
      requireEmail: true
      ## Maximum attempts before an email token is reset and a new email will need to be sent.
      emailAttempts: 3
      ## Email token validity in seconds.
      emailTokenExpiration: 600
      # Allow invited users to sign-up even feature is disabled: https://github.com/dani-garcia/vaultwarden/wiki/Disable-invitations
      allowInvitation: true
      ## Number of hours after which an organization invite token, emergency access invite token,
      ## email verification token and deletion request token will expire
      invitationExpiration: 12
      ## Allow users to set password hints. Applies to all users.
      #passwordHintsAllowed: true
      # Show password hints: https://github.com/dani-garcia/vaultwarden/wiki/Password-hint-display
      showPasswordHint: false
      ## Default organization name in invitation e-mails that are not coming from a specific organization.
      defaultInviteName: "fr3d"
      # Enable Web Vault (static content). https://github.com/dani-garcia/vaultwarden/wiki/Disabling-or-overriding-the-Vault-interface-hosting
      enableWebVault: true
      # Enable Bitwarden Sends globally  
      enableSends: true
      # Restrict creation of orgs. Options are: 'all', 'none' or a comma-separated list of users.
      emailChangeAllowed: true
      admin:
        # Enable admin portal.
        enabled: true
        # Disabling the admin token will make the admin portal accessible to anyone, use carefully: https://github.com/dani-garcia/vaultwarden/wiki/Disable-admin-token
        disableAdminToken: false
        ## Token for admin login, will be generated if not defined. https://github.com/dani-garcia/vaultwarden/wiki/Enabling-admin-page
        token:
        ## Use existing secret for the admin token. Key is 'admin-token'.
        existingSecret: admin-token
        #existingSecretKey: admin-token
      emergency:
        # Allow any user to enable emergency access.
        enabled: true
        ## Schedule to send expiration reminders to emergency access grantors. Cron schedule format.
        #reminder: "0 3 * * * *"
        ## Schedule to grant emergency access requests that have met the required wait time. Cron schedule format.
        #timeout: "0 3 * * * *"
      extraENV:
        IP_HEADER: None

      smtp:
        enabled: true
        host: "smtp.sendgrid.net"
        from: "vaultwarden@fr3d.dev"
        security: starttls
        port: 587
        AuthMechanism: Login
        existingSecret: vaultwarden-mail-creds    #existingSecretKey: smtp-user, smtp-password

      log:
        # Log to file.
        file: ""
        level: "debug"
      icons:
        service: google
        disableDownload: false
    service:
      type: ClusterIP
      httpPort: 80
      externalTrafficPolicy: Cluster
    ingress:
      enabled: true
      className: "tailscale"
      host: "dev-int-vaultwarden"
      annotations:
        #cert-manager.io/cluster-issuer: "letsencrypt-staging"
      tls:
        - secretName: vw-tls
          hosts:
            - dev-int-vaultwarden
    persistence:
      enabled: true
      size: 3Gi
      accessMode: ReadWriteOnce
      storageClass: "local-path"
    image:
      pullPolicy: IfNotPresent
      repository: vaultwarden/server
      #tag: "1.32.0"
    replicaCount: 1
    serviceAccount:
      create: true
      name: "vaultwarden-srv-acct"
