---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: pgadmin
  namespace: flux-system
spec:
  interval: 24h
  url: https://helm.runix.net
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: runix/pgadmin4
      version: "1.47.0"
      sourceRef:
        kind: HelmRepository
        name: pgadmin
        namespace: flux-system
      interval: 12h
  targetNamespace: database
  values:
    serviceAccount:
      create: true
    serverDefinitions:
      enabled: true
      resourceType: ConfigMap
    preferences:
      enabled: false
    ingress:
      enabled: true
      ingressClassName: tailscale
      hosts:
        - host: dev-pgadmin
          path:
            - path: /
              pathType: Prefix
    existingSecret: "pgadmin-creds"
    secretKeys:
        pgadminPasswordKey: password
