apiVersion: v1
data:
    password: ENC[AES256_GCM,data:W/IMnY6lTc9IERFBmGRxPTfFTp2xXfEBbXbeGyarvp4KvrDOGldmkN8SOlA=,iv:actxtXAW4OBD2hU+DYTc4R3iNiOKxvMn2R/MIoIC/Ok=,tag:jLmlpjfiC2IvvcwGluI0YA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: pgadmin-creds
    namespace: database
sops:
    age:
        - recipient: age1vml3vk5uzyztj96qgz7n0a6w8ynvtmxfarkp0jdl0hvcj003895qcp6z09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTHh5dW1keEdUdkR4eW5G
            WjFydmYvSlBTZkxYcXdxRGUxSko4cG5wQ1JNCk52aCs2WmJVUCs4MFBjWDJkeVRi
            U2tENXE2ODJnczhsUFQ1RkZBeXFmdGcKLS0tICtNbzVVeElraGdZVTM3bms1SzVP
            UGpmOEtEYlllNWdjS3dzUjQvVllsRVkK3zBU78qQtb8BbRkzDAyjIxnzz4zeGrTQ
            Jv0cDzzpohf2f0Zt0DeQMIL+Dd8N1ozWNiF6aTKoBIzLTnLFJi3FZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-24T18:58:00Z"
    mac: ENC[AES256_GCM,data:uro+V6Gh9mJ4nDiUj/5hafrOsPBbhfgXk22yr4W4JzahI9XJEtVFaDBBWrmgfxeJ8DAtbpjgccO3lxP61FiTsg1SB2RDEcEL7WEono1OjcECAghj4OWv6tWT8sqrtZyct8n2WjKrrP4u542pUVng3upqktr4YFvcEk51fIADarg=,iv:V3ZCO+3f+XE4xwXLhBoW3APTCzbLq0HJz75GziugWbk=,tag:ydH09LKt0vXdMVSz+f6iig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
