---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: pgadmin
  namespace: pgadmin
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
    - mfsymlinks
    - nobrl
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: pgadmin
    volumeAttributes:
      source: //10.3.3.11/Home-Share
    nodeStageSecretRef:
      name: smbcreds
      namespace: storage
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-pgadmin
  namespace: pgadmin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pgadmin
  storageClassName: smb
