---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: dev-pgadmin-2
  namespace: database
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=5050
    - gid=5050
    - mfsymlinks
    - nobrl
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: dev-pgadmin-2
    volumeAttributes:
      source: //10.3.3.11/Home-Share/dev/pgadmin
    nodeStageSecretRef:
      name: smbcreds
      namespace: storage
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-dev-pgadmin-2
  namespace: database
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: dev-pgadmin-2
  storageClassName: smb
