apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argo-cd
spec:
  project: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
  sources:
  - repoURL: 'https://pkgs.tailscale.com/helmcharts'
    chart: tailscale-operator
    targetRevision: 1.70.0
    helm:
      valueFiles:
      - $values/tailscale/values/values.yaml
  - repoURL: 'git@github.com:alexrf45/dev-argo.git'
    targetRevision: main
    ref: values
