apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../../base/kube-prometheus-stack.yaml
patches:
  - path: ./patch.yaml
    target:
      kind: HelmRelease
