apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
spec:
  chart:
    spec:
      version: "2.29.1"
  values:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
      enabled: true
      hosts:
      - staging.internal.pihole.fr3d.dev
      ingressClassName: cilium
      path: /
      pathType: Prefix
      tls:
      - hosts:
        - staging.internal.pihole.fr3d.dev
        secretName: pihole-tls
    persistentVolumeClaim:
      enabled: true
      storageClass: local-path
      accessModes:
        - ReadWriteOnce
      size: 2048Mi
    mixedService: true
