apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  chart:
    spec:
      version: "1.9.1"
  values:
    defaultSettings:
      deletingConfirmationFlag: false
      snapshotMaxCount: 3
      storageMinimalAvailablePercentage: 10
      v2DataEngine: true

    longhornUI:
      replicas: 1
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 2
      defaultDataLocality: best-effort
      migratable: true
      reclaimPolicy: Delete
      backingImage:
        enable: true
      dataEngine: v2
    preUpgradeChecker:
      jobEnabled: true
      upgradeVersionCheck: true
    csi:
      provisionerReplicaCount: 2
      snapshotterReplicaCount: 2
      resizerReplicaCount: 2
      attacherReplicaCount: 2
    service:
      manager:
        type: ClusterIP
        externalTrafficPolicy: Cluster
      ui:
        type: ClusterIP
        externalTrafficPolicy: Cluster
    metrics:
      serviceMonitor:
        enabled: true

