apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/pihole
  - storage-pihole-prod.yaml
  - secrets-smb.yaml
patches:
  - path: release.yaml
    target:
      kind: HelmRelease
