apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  namespace: database
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "PostgreSQL DB - Wallabag",
          "Group": "Servers",
          "Port": 5432,
          "Username": "app",
          "Host": "wallabag-dev-cluster-rw",
          "SSLMode": "prefer",
          "MaintenanceDB": "postgres"
        }
      }
    }
