apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: securecodebox-operator-metrics
    helm.toolkit.fluxcd.io/name: operator
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: securecodebox-operator-metrics
  namespace: monitoring
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: securecodebox-operator-metrics
