---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    env = "production"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    pod-security.kubernetes.io/enforce = "privileged"
    app = "cert-manager"
---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-system
  labels:
    pod-security.kubernetes.io/enforce = "privileged"
    app = "nginx-ingress"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pihole-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    pod-security.kubernetes.io/enforce = "privileged"
    app = "longhorn"
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    pod-security.kubernetes.io/enforce = "privileged
    app = "kube-prometheus-stack"

---
