---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: monitoring
        namespace: flux-system
      version: 72.3.0
  interval: 3m
  maxHistory: 3
  install:
    crds: CreateReplace
    remediation:
      retries: 4
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  values:
    crds:
      enabled: true
      upgradeJob:
        enabled: true
        forceConflicts: true
    defaultRules:
      create: false
    cleanPrometheusOperatorObjectNames: true
    alertmanager:
      enabled: false
    kubernetesServiceMonitors:
      enabled: true
    grafana:
      enabled: true
      prune: true
      namespaceOverride: "monitoring"
      admin:
        existingSecret: "grafana-secret"
      defaultDashboardsEditable: true
      defaultDashboardsEnabled: true
      defaultDashboardsTimezone: America/New_York
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-staging
        enabled: true
        hosts:
        - dev.int.grafana.home-0ps.com
        ingressClassName: cilium
        path: /
        tls:
        - hosts:
          - dev.int.grafana.home-0ps.com
          secretName: grafana-general-tls
      persistence:
        accessModes:
        - ReadWriteOnce
        enabled: true
        finalizers:
        - kubernetes.io/pvc-protection
        size: 2Gi
        storageClassName: local-path
      metricLabelsAllowlist:
        - pods=[*]
        - deployments=[*]
        - persistentvolumeclaims=[*]
    prometheus:
      enabled: true
      ingress:
        enabled: true
        pathType: Prefix
        ingressClassName: tailscale
        tls:
        - hosts:
          - dev-int-prom
          secretName: prometheus-general-tls
        hosts:
        - dev-int-prom

      prometheusSpec:
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        logFormat: logfmt
        logLevel: debug
        replicas: 2
        persistentVolumeClaimRetentionPolicy:
          whenDeleted: Delete
          whenScaled: Retain
        retention: 7d
        retentionSize: 2GB
        routePrefix: /
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              resources:
                requests:
                  storage: 2Gi
    prometheus-node-exporter:
       enabled: false
       prometheus:
        monitor:
          enabled: true
          relabelings:
            - action: replace
              regex: (.*)
              replacement: $1
              sourceLabels: ["__meta_kubernetes_pod_node_name"]
              targetLabel: kubernetes_node
    additionalPrometheusRulesMap:
      dockerhub-rules:
        groups:
          - name: dockerhub
            rules:
              - alert: DockerhubRateLimitRisk
                annotations:
                  summary: Kubernetes cluster Dockerhub rate limit risk
                expr: count(time() - container_last_seen{image=~"(docker.io).*",container!=""} < 30) > 100
                labels:
                  severity: critical
      oom-rules:
        groups:
          - name: oom
            rules:
              - alert: OomKilled
                annotations:
                  summary: Container {{ $labels.container }} in pod {{ $labels.namespace }}/{{ $labels.pod }} has been OOMKilled {{ $value }} times in the last 10 minutes.
                expr: (kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 10m >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}[10m]) == 1
                labels:
                  severity: critical
    prometheusOperator:
      enabled: true
      revisionHistoryLimit: 5
      tls:
        enabled: true
        tlsMinVersion: VersionTLS13
        certManager:
          admissionCert:
            duration: ""
          enabled: true
          issuerRef:
            kind: ClusterIssuer
            name: letsencrypt-staging
          rootCert:
            duration: ""
        internalPort: 10250

