---
apiVersion: v1
kind: Namespace
metadata:
  name: code-server
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    pod-security.kubernetes.io/enforce: &ps restricted
    pod-security.kubernetes.io/audit: *ps
    pod-security.kubernetes.io/warn: *ps 
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bjw-s
  namespace: flux-system
spec:
  interval: 10m
  timeout: 3m0s
  url: https://bjw-s.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: code-server
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  targetNamespace: code-server
  values:
    controllers:
      main:
        type: statefulset

        containers:
          main:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.98.2

            args:
              - --auth
              - none
              - --user-data-dir
              - /home/coder/.vscode
              - --extensions-dir
              - /home/coder/.vscode
              - --port
              - "8080"
              - --proxy-domain
              - &host "staging.internal.coder.fr3d.dev"
              - /home/coder

            env:
              DISABLE_TELEMETRY: "true"

            resources:
              requests:
                cpu: 10m
                memory: 640M
              limits:
                memory: 640M

        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch

    service:
      main:
        controller: main
        ports:
          http:
            port: &httpPort 8080

    ingress:
      main:
        className: cilium
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-staging
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: main
                  port: *httpPort
        tls:
          - secretName: "coder-tls"
            hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /home/coder
