---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  interval: 1m0s
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  chart:
    spec:
      chart: external-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: kube-system
  interval: 1m0s
  releaseName: external-secrets
  targetNamespace: kube-system
  values:
    certController:
      create: true
      replicaCount: 1
      requeueInterval: 5m
      revisionHistoryLimit: 5
    concurrent: 1
    crds:
      conversion:
        enabled: true
      createClusterExternalSecret: true
      createClusterSecretStore: true
      createPushSecret: true
    createOperator: true
    dnsPolicy: ClusterFirst
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/external-secrets/external-secrets
    installCRDs: true
    log:
      level: info
      timeEncoding: epoch
    processClusterExternalSecret: true
    processClusterStore: true
    processPushSecret: true
    replicaCount: 1
    revisionHistoryLimit: 4
