---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: pihole-system
spec:
  chart:
    spec:
      chart: external-dns
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: pihole-system
      version: 8.0.1
  interval: 1m0s
  releaseName: external-dns
  targetNamespace: pihole-system
  values:
    extraEnvVars:
    - name: EXTERNAL_DNS_PIHOLE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: pihole-password
    ingressClassFilters:
    - nginx-internal
    pihole:
      server: http://pihole-web.pihole-system.svc.cluster.local
    policy: upsert-only
    provider: pihole
    serviceAccount:
      create: true
      name: external-dns
    txtOwnerId: homelab
