apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-issuers.yaml
  - releases.yaml
  - repositories.yaml
  - longhorn.yaml
  - pihole.yaml
  - kube-prometheus-stack.yaml
  - extranal-dns.yaml
