apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    pod-security.kubernetes.io/enforce = "privileged"
    app = "longhorn"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: storage
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://charts.longhorn.io

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: storage
  namespace: flux-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: storage
        namespace: flux-system
      version: 1.7.1
  interval: 1m0s
  releaseName: longhorn
  targetNamespace: storage
  values:
    csi:
      attacherReplicaCount: 2
      provisionerReplicaCount: 2
      resizerReplicaCount: 2
      snapshotterReplicaCount: 2
    defaultSettings:
      deletingConfirmationFlag: false
      snapshotMaxCount: 3
    image:
      csi:
        attacher:
          repository: longhornio/csi-attacher
          tag: v4.6.1
        livenessProbe:
          repository: longhornio/livenessprobe
          tag: v2.14.0
        nodeDriverRegistrar:
          repository: longhornio/csi-node-driver-registrar
          tag: v2.12.0
        provisioner:
          repository: longhornio/csi-provisioner
          tag: v4.0.1
        resizer:
          repository: longhornio/csi-resizer
          tag: v1.11.1
        snapshotter:
          repository: longhornio/csi-snapshotter
          tag: v7.0.2
      longhorn:
        backingImageManager:
          repository: longhornio/backing-image-manager
          tag: v1.7.1
        engine:
          repository: longhornio/longhorn-engine
          tag: v1.7.1
        instanceManager:
          repository: longhornio/longhorn-instance-manager
          tag: v1.7.1
        manager:
          repository: longhornio/longhorn-manager
          tag: v1.7.1
        shareManager:
          repository: longhornio/longhorn-share-manager
          tag: v1.7.1
        supportBundleKit:
          repository: longhornio/support-bundle-kit
          tag: v0.0.42
        ui:
          repository: longhornio/longhorn-ui
          tag: v1.7.1
      openshift:
        oauthProxy:
          repository: longhornio/openshift-origin-oauth-proxy
          tag: 4.15
      pullPolicy: IfNotPresent
    longhornUI:
      replicas: 1
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 2
      defaultDataLocality: best-effort
      defaultFsType: ext4
      defaultNodeSelector:
        enable: false
        selector: node
      migratable: false
      nfsOptions: vers=4.2,noresvport,softerr,timeo=600,retrans=5
      reclaimPolicy: Delete
    preUpgradeChecker:
      jobEnabled: true
      upgradeVersionCheck: true
    service:
      manager:
        type: ClusterIP
        externalTrafficPolicy: Cluster
      ui:
        type: ClusterIP
        externalTrafficPolicy: Cluster

