---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: monitoring
        namespace: flux-system
      version: 70.9.0
  interval: 3m
  maxHistory: 5
  install:
    crds: CreateReplace
    remediation:
      retries: 4
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  values:
    crds:
      enabled: true
      upgradeJob:
        enabled: true
        forceConflicts: true
    defaultRules:
      create: false
    cleanPrometheusOperatorObjectNames: true
    alertmanager:
      enabled: false
    kubernetesServiceMonitors:
      enabled: true
    grafana:
      enabled: true
      prune: true
      namespaceOverride: "monitoring"
      admin:
        existingSecret: "grafana-secret"
      defaultDashboardsEditable: true
      defaultDashboardsEnabled: true
      defaultDashboardsTimezone: America/New_York
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        enabled: true
        hosts:
        - prod-internal-grafana
        ingressClassName: tailscale
        path: /
        tls:
        - hosts:
          - prod-int-grafana
         # secretName: grafana-general-tls
      persistence:
        accessModes:
        - ReadWriteOnce
        enabled: true
        finalizers:
        - kubernetes.io/pvc-protection
        size: 10Gi
        storageClassName: local-path
        type: sts
    nodeExporter:
      enabled: false
    prometheus:
      enabled: true
      thanosService:
        enabled: false
      ingress:
        enabled: true
        pathType: Prefix
        ingressClassName: cilium
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        tls:
        - hosts:
          - prod.int.prometheus.fr3d.dev
          secretName: prometheus-general-tls
        hosts:
        - prod.int.prometheus.fr3d.dev

      prometheusSpec:
        logFormat: logfmt
        logLevel: info
        replicas: 2
        persistentVolumeClaimRetentionPolicy:
          whenDeleted: Delete
          whenScaled: Delete
        retention: 7d
        retentionSize: 10GB
        routePrefix: /
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              resources:
                requests:
                  storage: 10Gi
    prometheus-node-exporter:
       enabled: false
       fullnameOverride: node-exporter
       prometheus:
        monitor:
          enabled: true
          relabelings:
            - action: replace
              regex: (.*)
              replacement: $1
              sourceLabels: ["__meta_kubernetes_pod_node_name"]
              targetLabel: kubernetes_node
    additionalPrometheusRulesMap:
      dockerhub-rules:
        groups:
          - name: dockerhub
            rules:
              - alert: DockerhubRateLimitRisk
                annotations:
                  summary: Kubernetes cluster Dockerhub rate limit risk
                expr: count(time() - container_last_seen{image=~"(docker.io).*",container!=""} < 30) > 100
                labels:
                  severity: critical
    prometheusOperator:
      enabled: true
      revisionHistoryLimit: 5
      tls:
        enabled: true
        tlsMinVersion: VersionTLS13
        certManager:
          admissionCert:
            duration: ""
          enabled: true
          issuerRef:
            kind: ClusterIssuer
            name: letsencrypt-production
          rootCert:
            duration: ""
        internalPort: 10250

