---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: pv-smb-pihole-dev
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: pihole
    volumeAttributes:
      source: //10.3.3.11/home-data/pihole-dev
    nodeStageSecretRef:
      name: smbcreds
      namespace: storage
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-pihole-dev-smb
  namespace: networking
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-smb-pihole-dev
  storageClassName: smb
