apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argo-cd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Dev Project Space

  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - 'git@github.com:alexrf45/dev-argo.git'
    - '*'

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
 
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  # Destination clusters can be identified by 'server', 'name', or both.
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
    name: '*'

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false

  roles:
  # A role which provides read-only access to all applications in the project
  - name: dev
    description: dev role
    policies:
        - p, proj:dev:dev, applications, *, prod/*, allow

    jwtTokens:
    - iat: 1535390316

