---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: monitoring
        namespace: flux-system
      version: 72.3.0
  interval: 3m
  maxHistory: 3
  install:
    crds: CreateReplace
    remediation:
      retries: 4
  upgrade:
    crds: CreateReplace
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  values:
    crds:
      enabled: true
      upgradeJob:
        enabled: true
        forceConflicts: true
    defaultRules:
      create: true
      rules:
        alertmanager: false
        etcd: false
        configReloaders: true
        general: true
        k8sContainerCpuUsageSecondsTotal: true
        k8sContainerMemoryCache: true
        k8sContainerMemoryRss: true
        k8sContainerMemorySwap: true
        k8sContainerResource: true
        k8sContainerMemoryWorkingSetBytes: false
        k8sPodOwner: true
        kubeApiserverAvailability: true
        kubeApiserverBurnrate: false
        kubeApiserverHistogram: false
        kubeApiserverSlos: false
        kubeControllerManager: true
        kubelet: true
        kubeProxy: false
        kubePrometheusGeneral: true
        kubePrometheusNodeRecording: true
        kubernetesApps: true
        kubernetesResources: true
        kubernetesStorage: true
        kubernetesSystem: true
        kubeSchedulerAlerting: false
        kubeSchedulerRecording: false
        kubeStateMetrics: true
        network: true
        node: true
        nodeExporterAlerting: true
        nodeExporterRecording: true
        prometheus: true
        prometheusOperator: true
        windows: false
    cleanPrometheusOperatorObjectNames: true
    alertmanager:
      enabled: false
    kubernetesServiceMonitors:
      enabled: true
    grafana:
      enabled: true
      prune: true
      namespaceOverride: "monitoring"
      admin:
        existingSecret: "grafana-secret"
      defaultDashboardsEditable: true
      defaultDashboardsEnabled: true
      defaultDashboardsTimezone: America/New_York
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-staging
        enabled: true
        hosts:
        - test.int.grafana.fr3d.dev
        ingressClassName: cilium
        path: /
        tls:
        - hosts:
          - test.int.grafana.fr3d.dev
          secretName: grafana-general-tls
      persistence:
        accessModes:
        - ReadWriteOnce
        enabled: false
        finalizers:
        - kubernetes.io/pvc-protection
        size: 1Gi
        storageClassName: longhorn
        #type: sts
    nodeExporter:
      enabled: true
    kubeApiServer:
      serviceMonitor:
        selector:
          k8s-app: kube-apiserver
    kubeScheduler:
      service:
        selector:
          k8s-app: kube-scheduler
    kubeControllerManager:
      service:
        selector:
          k8s-app: kube-controller-manager
    kube-state-metrics:
      fullnameOverride: kube-state-metrics
      metricLabelsAllowlist:
        - pods=[*]
        - deployments=[*]
        - persistentvolumeclaims=[*]
    prometheus:
      enabled: true
      thanosService:
        enabled: false
      ingress:
        enabled: true
        pathType: Prefix
        ingressClassName: cilium
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-staging
        tls:
        - hosts:
          - test.int.prom.fr3d.dev
          secretName: prometheus-general-tls
        hosts:
        - test.int.prom.fr3d.dev

      prometheusSpec:
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        logFormat: logfmt
        logLevel: debug
        replicas: 2
        persistentVolumeClaimRetentionPolicy:
          whenDeleted: Delete
          whenScaled: Retain
        retention: 7d
        retentionSize: 1GB
        routePrefix: /
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              resources:
                requests:
                  storage: 2Gi
    prometheus-node-exporter:
       enabled: true
       fullnameOverride: node-exporter
       prometheus:
        monitor:
          enabled: true
          relabelings:
            - action: replace
              regex: (.*)
              replacement: $1
              sourceLabels: ["__meta_kubernetes_pod_node_name"]
              targetLabel: kubernetes_node
    additionalPrometheusRulesMap:
      dockerhub-rules:
        groups:
          - name: dockerhub
            rules:
              - alert: DockerhubRateLimitRisk
                annotations:
                  summary: Kubernetes cluster Dockerhub rate limit risk
                expr: count(time() - container_last_seen{image=~"(docker.io).*",container!=""} < 30) > 100
                labels:
                  severity: critical
      oom-rules:
        groups:
          - name: oom
            rules:
              - alert: OomKilled
                annotations:
                  summary: Container {{ $labels.container }} in pod {{ $labels.namespace }}/{{ $labels.pod }} has been OOMKilled {{ $value }} times in the last 10 minutes.
                expr: (kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 10m >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}[10m]) == 1
                labels:
                  severity: critical
    prometheusOperator:
      enabled: true
      revisionHistoryLimit: 5
      tls:
        enabled: true
        tlsMinVersion: VersionTLS13
        certManager:
          admissionCert:
            duration: ""
          enabled: true
          issuerRef:
            kind: ClusterIssuer
            name: letsencrypt-staging
          rootCert:
            duration: ""
        internalPort: 10250

