apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.yaml
  - svc.yaml
  - svcacct.yaml
  - clusterrole.yaml
  - configmap.yaml
  - deployment.yaml
  #- ingress.yaml
