apiVersion: v1
kind: Service
metadata:
  name: prod-homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: homepage
