---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: flux-system
spec:
  interval: 10m
  releaseName: homepage
  chartRef:
    kind: OCIRepository
    name: homepage
  values:
    replicaCount: 2
    ingress:
      enabled: true
      ingressClassName: tailscale
      hosts:
        - host: dev-homepage
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: dev-homepage-tls
          hosts:
            - dev-homepage
    nodeSelector:
      node: "worker"
