apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: name-onepassword-connect
  namespace: onepassword
spec:
  endpointSelector:
    matchLabels:
      name: onepassword-connect
  ingress:
  - {}
  egress:
  - toEndpoints:
    - matchLabels:
        app: onepassword-connect
        version: 1.7.3
    toPorts:
    - ports:
      - port: '8080'
        protocol: TCP
