apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      version: 0.20.2

  interval: 1m0s
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3

  releaseName: external-secrets
  targetNamespace: external-secrets
  values:
    global:
      nodeSelector:
        node: "worker"
    log:
      level: info
      timeEncoding: epoch
    installCRDs: true
    crds:
      createClusterExternalSecret: true
      createClusterSecretStore: true
      createPushSecret: true
    serviceMonitor:
      enabled: false
      namespace: "monitoring"
    grafanaDashboard:
      enabled: true
    replicaCount: 1
    revisionHistoryLimit: 15
