apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-infra
  namespace: flux-system
spec:
  dependsOn:
    - name: configs
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./monitoring/staging
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
