---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool
  namespace: networking
spec:
  addresses:
    - 10.3.3.50-10.3.3.100

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: home
  namespace: networking
spec:
  ipAddressPools:
  - pool
