---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: homelab
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: homelab
  policy:
    semver:
      range: 2.x.x
