---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: homelab-blog
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: fonalex45/homelab
  policy:
    semver:
      range: 2.x.x
