---
apiVersion: v1
kind: Namespace
metadata:
  name: spegel
  labels:
    pod-security.kubernetes.io/enforce: "privileged"
    app: "spegel"
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: spegel
  namespace: spegel
spec:
  type: "oci"
  interval: 5m0s
  url: oci://ghcr.io/spegel-org/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spegel
  namespace: spegel
spec:
  interval: 1m
  maxHistory: 3
  chart:
    spec:
      chart: spegel
      version: v0.0.30
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: spegel
  values:
    spegel:
      mirrorResolveTimeout: "10ms"
      containerdRegistryConfigPath: /etc/cri/conf.d/hosts

