---
all:
 children:
  server:
    hosts:
      home-4:
        ansible_host: 10.3.3.6
        ansible_user: sean
        ansible_ssh_private_key_file: "~/.ssh/fr3d"
      home-2:
        ansible_host: 10.3.3.4
        ansible_user: sean
        ansible_ssh_private_key_file: "~/.ssh/fr3d"

  agent:
    hosts:
      home-0:
        ansible_host: 10.3.3.2
        ansible_user: sean
        ansible_ssh_private_key_file: "~/.ssh/fr3d"
      home-1:
        ansible_host: 10.3.3.3
        ansible_user: sean
        ansible_ssh_private_key_file: "~/.ssh/fr3d"
      home-3:
        ansible_host: 10.3.3.5
        ansible_user: sean
        ansible_ssh_private_key_file: "~/.ssh/fr3d"
