---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: monitoring
        namespace: flux-system
      version: 68.4.5
  interval: 30m
  maxHistory: 3
  install:
    crds: CreateReplace
    remediation:
      retries: 4
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  values:
    crds:
      enabled: true
      upgradeJob:
        enabled: true
        nodeSelector:
          type: node
      serviceAccount:
        create: true
        name: ""
        automountServiceAccountToken: false
    alertmanager:
      enabled: true
      serviceMonitor:
        selfMonitor: true
        nodeSelector:
          type: node
    grafana:
      enabled: true
      namespaceOverride: "monitoring"
      admin:
        existingSecret: "grafana-secret"
      defaultDashboardsEditable: true
      defaultDashboardsEnabled: true
      defaultDashboardsTimezone: America/New_York
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-staging
          nginx.ingress.kubernetes.io/proxy-body-size: 20000m
        enabled: true
        hosts:
        - internal.grafana.fr3d.dev
        ingressClassName: cilium
        path: /
        tls:
        - hosts:
          - internal.grafana.fr3d.dev
          secretName: grafana-general-tls
      persistence:
        accessModes:
        - ReadWriteOnce
        enabled: true
        finalizers:
        - kubernetes.io/pvc-protection
        size: 20Gi
        storageClassName: proxmox-data
        type: sts
      serviceMonitor:
        enabled: true
        path: /metrics
    nodeExporter:
      enabled: true
      operatingSystems:
        linux:
          enabled: true
        aix:
          enabled: false
        darwin:
          enabled: false
    prometheus:
      enabled: true
      prometheusSpec:
        logFormat: logfmt
        logLevel: info
        persistentVolumeClaimRetentionPolicy:
          whenDeleted: Delete
          whenScaled: Retain
        retention: 7d
        retentionSize: 5GB
        routePrefix: /
        serviceMonitorSelector: {}
        serviceMonitorSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: proxmox-data
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
      serviceMonitor:
        selfMonitor: true
    prometheusOperator:
      enabled: true
      nodeSelector:
        type: node
      revisionHistoryLimit: 5
      tls:
        enabled: true
        tlsMinVersion: VersionTLS13
        certManager:
          admissionCert:
            duration: ""
          enabled: true
          issuerRef:
            kind: ClusterIssuer
            name: issuer
          rootCert:
            duration: ""
        internalPort: 10250
