---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss
  namespace: freshrss
  labels:
    app: freshrss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
        node: worker
    spec:
      containers:
      - name: freshrss
        image: freshrss/freshrss:1.27.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: freshrss-config
        env:
        # Auto-install configuration for first run
        # Uses multiline FRESHRSS_INSTALL env var format
        - name: FRESHRSS_INSTALL
          value: |
            --api-enabled
            --base-url $(BASE_URL)
            --db-base $(DB_NAME)
            --db-host $(DB_HOST)
            --db-password $(DB_PASSWORD)
            --db-type pgsql
            --db-user $(DB_USER)
            --default-user $(ADMIN_USER)
            --language en
        # Auto-create user configuration for first run
        - name: FRESHRSS_USER
          value: |
            --api-password $(ADMIN_API_PASSWORD)
            --email $(ADMIN_EMAIL)
            --language en
            --password $(ADMIN_PASSWORD)
            --user $(ADMIN_USER)
        # Database credentials from secret
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: freshrss-dev-creds
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: freshrss-dev-creds
              key: db_password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: freshrss-dev-creds
              key: db_name
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: freshrss-dev-creds
              key: db_host
        # Application credentials from secret
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: freshrss-dev-creds
              key: admin_user
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: freshrss-dev-creds
              key: admin_password
        - name: ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: freshrss-dev-creds
              key: admin_email
        - name: ADMIN_API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: freshrss-dev-creds
              key: admin_api_password
        - name: BASE_URL
          valueFrom:
            secretKeyRef:
              name: freshrss-dev-creds
              key: base_url
        volumeMounts:
        - name: data
          mountPath: /var/www/FreshRSS/data
        - name: extensions
          mountPath: /var/www/FreshRSS/extensions
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: freshrss-data-pvc
      - name: extensions
        persistentVolumeClaim:
          claimName: freshrss-extensions-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-data-pvc
  namespace: freshrss
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-extensions-pvc
  namespace: freshrss
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: iscsi
---
apiVersion: v1
kind: Service
metadata:
  name: freshrss
  namespace: freshrss
  labels:
    app: freshrss
spec:
  type: ClusterIP
  selector:
    app: freshrss
    node: worker
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: freshrss
  namespace: freshrss
spec:
  parentRefs:
  - name: dev-app-gateway
    namespace: networking
  hostnames:
  - dev.int.freshrss.home-0ps.com  # Adjust to your domain
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: freshrss
      port: 80
