---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freshrss-dev-db-creds
  namespace: freshrss
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: freshrss_dev_db
        property: username
    - secretKey: password
      remoteRef:
        key: freshrss_dev_db
        property: password
