apiVersion: v1
data:
    1password-credentials.json: ENC[AES256_GCM,data:mGWBNkGAzIo3zEHr9vyWDeFIL8UYxYqjSpL7mO01Qdq46Rr9THg9ht6U2WQb3ISiBsltEZofATE4mXEt/JT8v+vY7yaqt99C8nAueVyHFPSgnc0JVgkA3c3OfCODCtB6WLclZkCVX2WfEGDM++y8VDILPBzt9VGHy3V00ng+ldlCR3AhLK76Gf3pgaOZl5svsy6f0CQQmx5e2syvkCQUamMo3W2HchohfCgvJilEOMmohHlwPovcSfrbcTaI1+7kyhvWIZE1jjLenrDJj9lGh9Yn2dmbszoVUeju2hLmryX7J/SSQPE1UbR/aCXLVYUMF54jKcXQfrUBdkXy2KoIQboNhF7vO8rI0hKidMTImjUYqb8YT+8rn4HCDeJS9LqMx0avXgcqePXT+bGT/MwAfxi018P/5LGvC/tfOcPv9CXpkt2hojwvTgW2udwVzwIHQEmW+wqWhXnLa2uJjUVJ5537tKh4vRdTf//AT5tREk0pKjfDn1JnFiywgZ8TREbr5LIiZQ5/zUhyl5I/zp0NgnhEEQm7Lkb9E8nAHvYLyf6Zm/EijqSv7uhkOLRat5Lm2VlrIK784pEUBOgKXWwCu+TzytBacf8Pg02n9CpSLiQruK08Zj7kHdh99QBQM/q+ruOu3Xy+hgqAjSfrhEKiMFEPqGgfGjcPGL8VUMIkjk6WHdp3nA7YC5u1qus1ONy9vK2Ts6Zle/8Wte1xzDEs4SPLLsIJ39ARLzfQ6tfCqDBZtzvsTZYkdwOsfXD34Pk0XIef6wSsvAryUfng+uJmgZgje1MMrL1vRtBX83U63PRDp61/Ug5hSPmUq1FpnSnsAIUAS/6ktqlnCnnvGe6bW1fRXHjg0BgUmwuUTcF0lyxEpovtYqCaFfH1qH2Trh156wOkQScRY8e5391xK8B4LeoMs6RGhFCp1NvBmaSlO3oEZDdK+NzhRL7zeRWaV017tQ+2AB+8np0OrM1DizAACV0Y4+mRLzoCcTSrRmqudWFqKE879aCP8E9UCL05xy7dhT7Ck+oBMzbuJaQoFrXGd/VBzb9AvWKi3kjIDta3rf/hCrDYlOiXh1hGXYJ/oBvJzTBt/XUlCVLYB7PyxTFGsbm5muAvCgk6btMZXx6YSBKqloP7KJp8S0j4BTDD0BrLFhXGLAdpP54mKkUjcxJklMmDOqGE8hDMx7psh/GwSo0swP6bHFgU0Z9hLG21eUpOGecAsCmUogqhoJxf9DH9swBGVAPGA7w4MuffjmtIJIJYSoWnBFSzEBVgzXY9SNodUNna8nT/HGe459Pyu9kqaIL7oO5lqGfW7H0iu1RDe+SBU1O2G5nBmwHFvWekvvVeXadJ5buHYzHu57DkMpVXBKmj5eRrNmHasrM+Gn6rVjeN4CihL2N6ACQFEGuNuPX0UKnzDbF9RH1kruwh61ICvHm9UuaYUpUOvqdAHtfZuxSav1e7GFRf39gHrqHMyYPi8gQEj6YupWEDE5Ijz4PWdbnNF98Sbpo7qpeJV4Rp+lstNfu12LmSvrD6m8gNhUK6Qax5BB5mO0jlLpkb34szEoGkRpoyZtO9YvzaLzrOTrXe1kQy2kF8/ENFNCIAoNW/mAJMEJBT1Cfb9tPxoJN6Feisktbun09WAAytwuqKpU/9wID2N7/mIAv6VmKsq2CTXBXuQg9qNCiaob/ZHmUMt9P522N8yeZc5mdYXMgf6uPSBZdcC32TnxXcq+v8+6YwFpZ9k8t7JPTfkupSqy/Q9uq6ML74bfdUY9rv5wQK1dVmdUTVGWkBIHfiNqwTH4ER2KKjE5NQh+pxngPPnSYek+IftPFgJb8TsB+/om/hxAxI5hJNKeePd/9dI0q5e4OASaAZsjsn09u25UztbnTfZL9DwU8eefpPgrOedeMjzu31j36p0RZzMruO52DcqIn8VFs7I/qGYThCddGD,iv:BgHyNDyCZonzhzTnzPY9x1DNrz8EG/vGrX8JXkE4KiA=,tag:BUylwdBg28IE0Y+YeR4uoA==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2025-03-02T08:29:56Z"
    name: onepassword-connect-secret
    namespace: onepassword
    resourceVersion: "2518649"
    uid: 7a16c30f-45ec-4110-a65b-1530fcc027c3
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vml3vk5uzyztj96qgz7n0a6w8ynvtmxfarkp0jdl0hvcj003895qcp6z09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbWovQUZwaldSQy9CbmZV
            bjBEUWxxRDJYV3VUeXc0cm1nWkRtUjN1OEFJCmNRZGZDVUlJbDhIc3dmeTl4VEJK
            NVFBOUd5SXdoVXVURU83bmlNNTJmcncKLS0tIEk5UWxZQU5rZHh5cDRKay9YRDky
            U3I3TlNuL1JWNHEvVFZZQis2RTFzUVUKluU0QJLP1+T35w5iOaQ7YIF7yGav4ocm
            nnty/XdAsJSP0bEsXrtcKPc3r7nuZvL4WR6SEgd4AI2zRrKfFbBmNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-02T08:30:19Z"
    mac: ENC[AES256_GCM,data:SLgPBrFAkRF3L8g/YuHiPkELV85SdrKFYTc58vvsIIlxJY7NbRDDf6jAj/uC3l/dh0kLyWWNSE2Eq7ZEJn281QuUcRI44jEIqwmC/DiD6BgYOVaIQGijKKo0p2UhW0pefAp28j5wdPIXaZWN9qkr951PqPA7y37oukpfRdeoycc=,iv:qjyD8VtiLNZTs8r47HwyXTHbhluVHRS7hGbgDXi72Jk=,tag:zHxjbrQRjdW994MkV+TKOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
