apiVersion: v1
data:
    token: ENC[AES256_GCM,data:ZlWvh3pC+EzLgfJy4Bu6cr7MZkZaGYoHuIUEsnkvv54qkTTKGmdVa0/lyaivgfIpqvXto7STdf6iNfXee40jS5CwY6wgTN8Q5rVKy7iT1aHSyRZsjctDezw3EZYygsxLVE+aorBXM+f/CAH90z3AG/SoZ1dpcolkXXnYYqkrWuTAP+lPgv+DgJ7dNZVHEeu1Kpp8EpWJkzcNwd4qapH9o9hkImcNo7404Rg0tCMVTZS80Xxmn8LdFUPs2CNfUh0ekLbyi2JnaQjK1RS972+AvwjHg6Eu/u5TW/VjH3EDKgfRbCGQaSYmV5sbFGJTXzBYkYSsYopIjfpSMuU8sxdHLF3jv7O0/omRbWv283Tt8WLBHzHKIfp2q1alb/rGKutuuQqG+dmfb5OA/TUuGyYmFJd3BaccEQUIpB6HPUZJfjRBwLaAWEciPU8C6xn4GfW69ToEt1JHmRHKw0O/bogA4GKVhFxp1IklpnLqIZcAM7fT+t3w1XAuRKFVT3t4IJcMALFGEOCimdzekU5sb4GzSMTzr6aFtrY0u+0x+yeclsagiOy2bBrpjQythrlMWiTN0hjpBj36tjExcdjLLcw7/ekv4UWDeWDRdYL3OdAHlV8sbQ12ZSd1AGAL2yWyKw1NceoUmExF+Bs8QrQ94FndT6sC+c2Ra38Ystiq0hjap9LUPMAMNnEZO3kEoFlkYAqjB/SiA9y6BCpvcDlVEDdF9DM95O+vVCmFvbStyHB3kBWhku6NrG93cSAaHlbvqtrDzZvt/fdcdnuqR/Vtfy0QBrQQTnfM2G/ShWMpw16m8xB8cK0ku9Fhbcm1xdZ+nOruOXOASH7I+wZbpFsrrWI6fM8Ovns/TyRbTExl8rUOmABu74Ni/CSBMmzOEnJHODOocyaPPeCQazJAE3SZJtLpUxTiQgm4xBUPpk/ynF8/F0Jjn37YkvERzNg4HllZABysXg6mU3BsMKTg9rErQqzM33DT1BduNpTCtUKt5rRBG5xNK0+3gyaCaKjLt8XwAWNzSYLmoRRsQurKQOif3xQ5P52Dkujomn7umvV5R5IT7dSZD4/y2Y/WKdlX7JDtIJuteE/Knfxhy7LFereeWL+bbiF6IektpyOUfAEXgg4wN5Q4xFbrwCLp0cJcDnQ=,iv:6rVdm3YyXbsxmLqjo+cZhhx3SqxFnBeKonoqodSIo5Y=,tag:I+9wNoLyepwd6zu9WQPh+A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: onepassword-token
    namespace: onepassword
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vml3vk5uzyztj96qgz7n0a6w8ynvtmxfarkp0jdl0hvcj003895qcp6z09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcTVWNUtKWXJwUytPNXdx
            MG9qU2toTGFUbVoxeEpvYWxJOHlBc1h1ZlMwClhkTk50UUZjOUxOTUxxWGlNZTdy
            a2Nzbk9EVm1mc292UzlQSVBGVGovRXcKLS0tIFEwQmVhTzhMYzhoQ3FKSkhnLzJJ
            c2thaGlTSVNDcHJ2OFBmODhwZVIyazgKGIxWkkjJpyDrnFCsAKbvVqy151SyAwp9
            yvnEWJpMVbx739EqVkkiX/YoeKQGXdHGloITOyXBzm5zBOAC5Y7LAw==
            -----END AGE ENCRYPTED FILE-----
    mac: ENC[AES256_GCM,data:XrjDZPfcbiYwlyoXW5vBuIWMWeZ5BMmQSksmqvEBbaTGPS9h/HU8eHOs79vSkDrgslYQ5KeHG2nirAReKH/f+zUI6bQQ1pWe76R0trE25691uk10LsudhEbCfF0KkpfrTA+jwnqPyBm8V+IuzynOUSad5stRC/TJZ2RStsFucnc=,iv:iLmh41rT9ckH5NZd4EN8G6wADeRWJsHyrFwAM7NB8ao=,tag:V5aizQ52Hm3pl2Rf6CxfJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
