---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-csi
  namespace: flux-system
spec:
  chart:
    spec:
      chart: proxmox-csi-plugin
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: proxmox-csi-plugin
        namespace: flux-system
      version: 0.3.4
  interval: 1m0s
  maxHistory: 3
  install:
    crds: CreateReplace
    remediation:
      retries: 4
  releaseName: proxmox-csi-plugin
  targetNamespace: proxmox-csi
  values:
    config:
      clusters: []
      features:
        provider: default
    configFile: /etc/proxmox/config.yaml
    controller:
      attacher:
        args:
        - --default-fstype=ext4
        image:
          pullPolicy: IfNotPresent
          repository: registry.k8s.io/sig-storage/csi-attacher
          tag: v4.8.0
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
      plugin:
        image:
          pullPolicy: IfNotPresent
          repository: ghcr.io/sergelogvinov/proxmox-csi-controller
          tag: ""
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
      podAnnotations: {}
      provisioner:
        args:
        - --default-fstype=ext4
        image:
          pullPolicy: IfNotPresent
          repository: registry.k8s.io/sig-storage/csi-provisioner
          tag: v5.1.0
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
      resizer:
        args: []
        image:
          pullPolicy: IfNotPresent
          repository: registry.k8s.io/sig-storage/csi-resizer
          tag: v1.13.1
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
    createNamespace: false
    existingConfigSecret: null
    existingConfigSecretKey: config.yaml
    livenessprobe:
      failureThreshold: 5
      image:
        pullPolicy: IfNotPresent
        repository: registry.k8s.io/sig-storage/livenessprobe
        tag: v2.14.0
      initialDelaySeconds: 10
      periodSeconds: 60
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
      timeoutSeconds: 10
    logVerbosityLevel: 5
    metrics:
      enabled: true
      port: 8080
      type: annotation
    node:
      driverRegistrar:
        image:
          pullPolicy: IfNotPresent
          repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
          tag: v2.13.0
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
      kubeletDir: /var/lib/kubelet
      nodeSelector: {}
      plugin:
        image:
          pullPolicy: IfNotPresent
          repository: ghcr.io/sergelogvinov/proxmox-csi-node
          tag: ""
        resources: {}
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/unschedulable
        operator: Exists
      - effect: NoSchedule
        key: node.kubernetes.io/disk-pressure
        operator: Exists
    provisionerName: csi.proxmox.sinextra.dev
    replicaCount: 1
    storageClass: []
    timeout: 3m
