---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: proxmox-csi-plugin
  namespace: flux-system
spec:
  interval: 1m0s
  url: oci://ghcr.io/sergelogvinov/charts/proxmox-csi-plugin
  ref:
    semver: ">= 0.3.4"
