---
apiVersion: source.toolkit.fluxcd.io/v2
kind: OCIRepository
metadata:
  name: homepage
  namespace: default
spec:
  interval: 5m0s
  url: oci://ghcr.io/m0nsterrr/helm-charts/homepage
  ref:
    tag: latest
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/M0NsTeRRR/helm-charts/.*$"
