---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: homepage
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://ghcr.io/m0nsterrr/helm-charts/homepage
  ref:
    tag: latest
  # verify:
  #   provider: cosign
  #   matchOIDCIdentity:
  #     - issuer: "^https://token.actions.githubusercontent.com$"
  #       subject: "ghcr.io/m0nsterrr/helm-charts/homepage:3.3.0"
