apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cf-token
  namespace: cert-manager
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  data:
    - secretKey: cloudflare-token
      remoteRef:
        key: cf_token_home-0ps.com
        property: cloudflare-token
