apiVersion: v1
kind: Secret
metadata:
    name: dev-argo
    namespace: argo-cd
    labels:
        argocd.argoproj.io/secret-type: repository
stringData:
    type: ENC[AES256_GCM,data:W380,iv:B6xSE7xPYI7FLo2euecBWvH2k96TfIOpYNE0PGb0/KI=,tag:uJ2ysGHJJLVyyTnGr2liRQ==,type:str]
    url: ENC[AES256_GCM,data:faEkx+/7SX0CHQFAah92mQQx36nPoplPKvpEp4YZj6EJqXth,iv:o6fnRw9r45ldDoeGBeL8KgrMpJquUIk28tr6+tobFUE=,tag:Qjlom07DqQvDIZS2mv3vsg==,type:str]
    sshPrivateKey: ENC[AES256_GCM,data:paGbWYfZV1NBIY9tWoVSfXeQ86OUsk5igX30EwwfEHFzOpWHLJveHOTsKL90OKmM0Y7sPc0fmgyGzRtoxqFaGH49b7+hDklAkMCfGlyUOmRlfleJkxioNyjL25R/Jw4mQ6esLHERaLbOcqDKOehtYG5CckkbO7HlhUepzXHKld3mSJv9zykHoWBElq3gba4xDRFFWEJ2LoFKr2p6SebeDEI+kJtRgjiQ7fhflqSijSnNXcYRJ28hs1k2zot9X8TsQduKIvWdN4vtVpxvRnwrrOqhi5G03HX0gscMM3t/pbki4Y3Dwa4nyaTgws8Swd8bSG0vD2YDSc7+cGvHBD8KpZPFh40U1yDcZB5TWnuEXlpn562xYsYrAd68kqA7fqcIPvWQkqgCUmIodL43sZIZrU5L7yLEBmVtXypwd705smqzLnpuG5Sqb0bvx++FfHO4MOWTGv1S6T/yPjoH+wIdnYtdbbzqcI3tNEiM4O0W2qbF4+5JxGj5k4C43W9sYk7Ihg1G,iv:wKtRcAK6YMAejmtr6ziM5uZRbjDdix3aFPJFlc9X/oo=,tag:/oOWVAD+TXSFaWeV8HK5BQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vml3vk5uzyztj96qgz7n0a6w8ynvtmxfarkp0jdl0hvcj003895qcp6z09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZzRuOGZnL2lCdmtiVDZJ
            TmNmemowNXFoUThhc01DaUx3Y01zd2Nvb1ZnCnJQdUxGS0ZucGN4Q2ViQUkyZUlR
            S1VoZGs1TG1JdllWeWNnZHNURVhFSDAKLS0tIGdRYTcvaE5wUzN2VHFRejloVkZ3
            dkhDakYvbVludnlsempTaWhBMmNWRWMKugBngyecR6QCOQItqP1coTlWVPDIQmw9
            x3TWKV5ATKDEn0k/cflqrRAeG6WIJQq1S+snuWK3OFGi+thuTZ/zOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-17T23:17:12Z"
    mac: ENC[AES256_GCM,data:zX/wiOEImbQErQADgJn2srV9oWAzsn2ykvBti/kOiLk6i98DRM6jJ0hUG4dctyrAKYbZJOEjcRV7jQ0gWmrBfS8UaZ5uKnGauGzD4HD1ucOUNwsrPQrP8f6OI7T0xdrA/7uAn9ai6J8OLwI1y/UEuzws0Ec/Ge5Ln5kj1Zg9dDQ=,iv:eSp0CZYgEmxsErw1TgNqsL3sWF54rdcPjV9MQCBx3MQ=,tag:Piu28qM9jr2Z/63/Z7b8Lw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
