apiVersion: v1
data:
    slack-token: ENC[AES256_GCM,data:tUR8Y2e4iHfj+UVWBYNn3MF4oshaa4hLHXo3/MUjd3QQM1UwFYzKsppFtBCGbcoOoHsN3E8ym/sH4WflipgaeCo9P23kX6RyzpffWQ==,iv:P8CnBmvNYZIq55w9ErF6x+yydq3qoUur1qaN/APR12Q=,tag:KeFVmFhRVEc/tEfqjSKp5A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: argocd-notifications-secret
    namespace: argo-cd
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vml3vk5uzyztj96qgz7n0a6w8ynvtmxfarkp0jdl0hvcj003895qcp6z09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZY3NhM1RDNVFPUktsNkY2
            aGJDWTk2NU5GNEdTK1pQNm5RMm5nekcyYjJZCmtRSm9qcEZCNW0rQXM4RWpaUTY2
            bEYva3BhbUIwRTJWL2M5ZVVYWEJrZkEKLS0tIGZZUzFyWDA3aHJjaFQ2U2p0bWZh
            M3Yrb3Z3UnE5d0JzOTFWRWVnMk05eXcK2IFFpcOiVjSOlJ4f2cLHw3t9L4u4wMyW
            q3nBhRxRdAt4PNkT4iOqpSWv4xVlrII/Eo/96UyOvoxWat/WkH22Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-08T01:36:52Z"
    mac: ENC[AES256_GCM,data:pvOr0MdgkHSmyy90Szl4N3I0sbHLiy6DltRD4H3J/MkiIqMHZaWkU23VWh35hbsAuIqCthjllLHptWo2pFrjR+wU3xnuH7R2jwDr/TVeHq3kEZXESUFgyXm7ilEWnEtsoP0PeA0O4A9iUnLyotA5fIBOdS9WSCoRuMqz5yTJnbg=,iv:bjTJmSIxffseOUAHK2Flh2IpMjpgPbuVrjBWFYb2nmc=,tag:M1iy8GFr7KvPSj7WJmQHdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
