apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    name: database
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: demo-cluster
  namespace: test
spec:
  instances: 10

  storage:
    size: 1Gi
