---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly-importer
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: importer
      version: 1.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: firefly-iii
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 7
  targetNamespace: firefly
  values:
    replicaCount: 1
    trustedProxies: "**"
    fireflyiii:
      # -- The URL at which Firefly III is available. If you change this value, click the "Reauthenticate" button on the importer after opening it!
      url: "http://firefly-firefly-firefly-iii:80"
      # -- The URL at which you access Firefly III. Check https://docs.firefly-iii.org/data-importer/install/configure/#configure-fidi to find out if you should set this.
      vanityUrl: "https://firefly-dev.bun-dominant.ts.net"
      auth:
        existingSecret: "firefly-dev-creds"

    # -- Environment variables for the importer. See docs at: https://github.com/firefly-iii/data-importer/blob/main/.env.example
    config:
      existingSecret: "firefly-dev-creds"
      envValueFrom: {}
      env:
        IGNORE_DUPLICATE_ERRORS: "false"
        TZ: "America/New_York"
        ENABLE_MAIL_REPORT: true
      files:
        - mountPath: /var/www/html/storage/configurations
          name: test.txt
          content: |
            This is a test file with some content

    image:
      repository: fireflyiii/data-importer
      pullPolicy: Always
      tag: "version-1.7.8"

    service:
      type: ClusterIP
      port: 80

    ingress:
      enabled: true
      className: "cilium"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
      hosts:
        - dev.int.firefly-importer.home-0ps.com
      tls:
        - secretName: firefly-importer-dev-tls
          hosts:
            - dev.int.firefly-importer.home-0ps.com
