---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: firefly-iii-importer
  namespace: flux-system
spec:
  interval: 1h
  url: https://firefly-iii.github.io/kubernetes
---
