---
apiVersion: v1
kind: Namespace
metadata:
  name: onepassword
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: onepassword-connect
  namespace: flux-system
spec:
  interval: 1h
  url: https://1password.github.io/connect-helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: connect
      sourceRef:
        kind: HelmRepository
        name: onepassword-connect
      version: "1.17.1"
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  targetNamespace: onepassword
  values:
    connect:
      create: true
      replicas: 1
      api:
        name: connect-api
        imageRepository: 1password/connect-api
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 0.2
        httpPort: 8080
        httpsPort: 8443
        logLevel: info
        serviceMonitor:
          enabled: false
          interval: 30s
          path: "/metrics"
      sync:
        name: connect-sync
        imageRepository: 1password/connect-sync
        resources: {}
        httpPort: 8081
        logLevel: info
      applicationName: onepassword-connect
      host: onepassword-connect
      serviceType: ClusterIP
      credentialsName: onepassword-connect-secret
      credentialsKey: 1password-credentials.json

      # Determines if HTTPS Port if setup for the 1Password Connect
      # Services for 1Password Connect API and Sync
      tls:
        # Denotes whether the Connect API is secured with TLS
        enabled: false
        # The name of the secret containing the TLS key (tls.key) and certificate (tls.crt)
        secret: op-connect-tls

    operator:
      # Denotes whether the 1Password Operator will be deployed
      create: true
      replicas: 1
      autoRestart: true
      applicationName: onepassword-connect-operator
      pollingInterval: 600
      # 1Password Operator Token Configuration
      token:
        # The name of Kubernetes Secret containing the 1Password Connect API token
        name: onepassword-token
        key: token
