---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: filebrowser
  namespace: flux-system
spec:
  interval: 1m0s
  url: http://brandan-schmitz.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: flux-system
spec:
  chart:
    spec:
      chart: brandan-schmitz/Filebrowser
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: filebrowser
        namespace: flux-system
      version: 1.0.6
  install:
    remediation:
      retries: 3
  interval: 1m0s
  releaseName: filebrowser
  targetNamespace: filebrowser
  upgrade:
    crds: CreateReplace
  values:
    ingress:
      enabled: true
      className: "tailscale"
      hosts:
        - host: dev-blog
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: dev-blog-tls
          hosts:
            - dev-blog
    persistence:
      config: true
      type: persistentVolumeClaim
    database:
      enabled: true
      type: persistentVolumeClaim
