---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: flux-system
spec:
  chart:
    spec:
      chart: pihole
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
      version: 2.27.0
  interval: 1m0s
  releaseName: pihole
  targetNamespace: pihole-system
  values:
    DNS1: 1.1.1.1
    DNS2: 8.8.8.8
    admin:
      enabled: true
      existingSecret: pihole-password
      passwordKey: password
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
      enabled: true
      hosts:
      - pihole.fr3d.dev
      ingressClassName: nginx-internal
      path: /
      pathType: Prefix
      tls:
      - hosts:
        - pihole.fr3d.dev
        secretName: pihole-tls
    persistentVolumeClaim:
      accessModes:
      - ReadWriteOnce
      enabled: false
      size: 2048Mi
    serviceDhcp:
      enabled: false
    serviceWeb:
      type: ClusterIP
      externalTrafficPolicy: Cluster
    serviceDns:
      externalTrafficPolicy: Cluster
      mixedService: false
      annotations:
        #lbipam.cilium.io/ips: 10.3.3.82
        io.cilium/lb-ipam-sharing-key: pihole
      type: LoadBalancer
    podDnsConfig:
      enabled: true
      policy: "None"
      namservers:
        - 10.3.3.82
        - 8.8.8.8
    adlists:
      # everything but the kitchen sink
      - https://big.oisd.nl
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/pro.txt
      - https://raw.githubusercontent.com/RooneyMcNibNug/pihole-stuff/master/SNAFU.txt
      - https://someonewhocares.org/hosts/zero/hosts
      - https://v.firebog.net/hosts/static/w3kbl.txt
      - https://winhelp2002.mvps.org/hosts.txt
      # ads
      - https://adaway.org/hosts.txt
      - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
      - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
      - https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/popupads.txt
      - https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
      - https://v.firebog.net/hosts/AdguardDNS.txt
      - https://v.firebog.net/hosts/Admiral.txt
      - https://v.firebog.net/hosts/Easylist.txt
      # tracking
      - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
      - https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
      - https://hostfiles.frogeye.fr/multiparty-trackers-hosts.txt
      - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
      - https://v.firebog.net/hosts/Easyprivacy.txt
      - https://v.firebog.net/hosts/Prigent-Ads.txt
      - https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
      # dangerous stuff
      - https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
      - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
      - https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
      - https://phishing.army/download/phishing_army_blocklist_extended.txt
      - https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts_full
      - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
      - https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/hosts.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/tif.txt
      - https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
      - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe
      - https://raw.githubusercontent.com/RPiList/specials/refs/heads/master/Blocklisten/notserious
      - https://urlhaus.abuse.ch/downloads/hostfile/
      - https://v.firebog.net/hosts/Prigent-Crypto.txt
      - https://v.firebog.net/hosts/Prigent-Malware.txt
      - https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
      # spam
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
      - https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt
      - https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
      # bad reputation
      - https://paulgb.github.io/BarbBlock/blacklists/hosts-file.txt
      - https://raw.githubusercontent.com/autinerd/anti-axelspringer-hosts/master/axelspringer-hosts
      - https://raw.githubusercontent.com/autinerd/anti-bertelsmann-hosts/master/bertelsmann-hosts
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/gambling.txt
      - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Fake-Science
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts
      - https://www.github.developerdan.com/hosts/lists/hate-and-junk-extended.txt
      # device / service specific
      - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt
      - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
      - https://raw.githubusercontent.com/TheShawnMiranda/LG-TV-Ad-Block/master/list
      - https://www.github.developerdan.com/hosts/lists/amp-hosts-extended.txt
      # DOH (DNS is totalitarian in this network!)
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/doh.txt
      - https://raw.githubusercontent.com/jpgpi250/piholemanual/master/DOH/DOHadb.txt
