apiVersion: v1
data:
    password: ENC[AES256_GCM,data:r1aB2s6XHF5lc1q70kc57mCt4fmQkjV1QY/Fwolqa/80gn5S3nYuLG3ojum4HAme34MYS9HS7QVUl2PAK+UFLexio1LO33oZ0Jdp4692Jn+OYeShwhTPLTKiorQ=,iv:TofbUwUkESR/K/REazfdGcYS5aiOH1MTpXsNHBuy4Ig=,tag:khOS/qavJoU6BpLPx8nCdg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: pihole-password
    namespace: pihole-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vml3vk5uzyztj96qgz7n0a6w8ynvtmxfarkp0jdl0hvcj003895qcp6z09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MTNBL2doKytSM3o4aUN6
            eDJvNlpDSVo2aTNIdVpkUCtlSlh6TENtN1Q4ClhJQnpDeVhmVUtqVHJoS0FDQWxQ
            ZEg2MUdHRW9sdFJ5N0hRVzhwdFNWUVEKLS0tIEdsbU5pU0dyMDdRQ3dOOHN1L0RW
            OUZwVStDenZYellSS09iZTFNbDYzN2cKIqLa92dMxmmodrRZYX1Mu7bqIpKqu9Ye
            63ZdKQzD7AUaW2YInZWkPQJvThhc8frzToFM+L9KTZGOJDg5hGCKUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-25T22:03:07Z"
    mac: ENC[AES256_GCM,data:kZEsV9i73mmJEcdF3SiM87TXst1msRuC19YthEQPgSXK69ep6S1xf6YoX5o8Nx4zEsPiEEzIDNVfangamLrknNTgFvASvg82KGmL799h4S6wnE+mPnq9mDZnyTK8WW0LLr/qD6lUXTpFd7Hw+6AjGUl+wiroDe+TghcUo794TTo=,iv:q+78uO4qWPJZOACBXEnzIz3Mirs1UjGDaxaWhzI0yTM=,tag:7Zvuh6UwOXmiJRohlZQrUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
