---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    pod-security.kubernetes.io/enforce: "privileged"
    app: "storage"
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: democratic-csi
  namespace: flux-system
spec:
  interval: 12h
  url: https://democratic-csi.github.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.7
      sourceRef:
        name: democratic-csi
        kind: HelmRepository
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  targetNamespace: storage
  values:
    csiDriver:
      name: local-path.cluster.local
      storageCapacity: true
      attachRequired: false
      fsGroupPolicy: File

    storageClasses:
      - name: local-path
        defaultClass: true
        reclaimPolicy: Delete
        volumeBindingMode: WaitForFirstConsumer
        allowVolumeExpansion: true
    # volumeSnapshotClasses:
    #   - name: local-hostpath
    #     deletionPolicy: Delete
    #     parameters:
    #       cluster: k8s
    controller:
      enabled: true
      strategy: node
      externalProvisioner:
        image: registry.k8s.io/sig-storage/csi-provisioner:v5.2.0
        extraArgs:
          - --leader-election=false
          - --node-deployment=true
          - --node-deployment-immediate-binding=false
          - --feature-gates=Topology=true
          - --strict-topology=true
          - --enable-capacity=true
          - --capacity-ownerref-level=1
      externalResizer:
        enabled: false
      externalAttacher:
        enabled: false
      externalSnapshotter:
        enabled: false
        extraArgs:
          - --leader-election=false
          - --node-deployment=true
    node:
      driver:
        image: ghcr.io/democratic-csi/democratic-csi:v1.9.3
        extraVolumeMounts:
          - name: local-hostpath
            mountPath: &path /var/data
            mountPropagation: Bidirectional
      extraVolumes:
        - name: local-hostpath
          hostPath:
            path: *path
            type: DirectoryOrCreate
    driver:
      config:
        driver: local-hostpath
        instance_id: k8s-local-hostpath
        local-hostpath:
          shareBasePath: *path
          controllerBasePath: *path
          dirPermissionsMode: "0770"
          dirPermissionsUser: 0
          dirPermissionsGroup: 0
