---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
  labels:
    app: "redis_cache_operations"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ot-helm
  namespace: flux-system
spec:
  interval: 24h
  url: https://ot-container-kit.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: redis-operator
      version: "0.21.0"
      sourceRef:
        kind: HelmRepository
        name: ot-helm
        namespace: flux-system
      interval: 6h
  targetNamespace: redis
  values:
    redisOperator:
      name: redis-operator
      imageName: ghcr.io/ot-container-kit/redis-operator/redis-operator
      imageTag: "0.21.0"
      imagePullPolicy: Always
      webhook: false
      automountServiceAccountToken: true
      pprof:
        enabled: true
        bindAddress: ":6060"
      metrics:
        enabled: true
        bindAddress: ":8080"
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 500m
        memory: 500Mi
    replicas: 1
    service:
      name: webhook-service
      namespace: redis
    certificate:
     name: redis-operator
     secretName: redis-operator-tls
    issuer:
      create: false
      kind: ClusterIssuer
      type: acme
      name: letsencrypt-staging
      email: homelab@fr3d.dev
      server: https://acme-staging-v02.api.letsencrypt.org/directory
      privateKeySecretName: letsencrypt-staging
      solver:
        enabled: false
    certmanager:
      enabled: true
      apiVersion: "cert-manager.io/v1"
    nodeSelector:
      node: "worker"
