# HTTPRoute for routing traffic to SilverBullet
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: silverbullet
  namespace: silverbullet
  labels:
    app.kubernetes.io/name: silverbullet
    app.kubernetes.io/component: route
spec:
  parentRefs:
    - name: prod-app-gateway
      namespace: networking
      sectionName: https
  hostnames:
    - "prod.int.silverbullet.home-0ps.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: silverbullet
          port: 80
          weight: 1
      timeouts:
        request: 60s
        backendRequest: 60s
---
# HTTP to HTTPS redirect route
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: silverbullet-redirect
  namespace: silverbullet
  labels:
    app.kubernetes.io/name: silverbullet
    app.kubernetes.io/component: route
spec:
  parentRefs:
    - name: prod-app-gateway
      namespace: networking
      sectionName: http
  hostnames:
    - "prod.int.silverbullet.home-0ps.com"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
