---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-silverbullet-pvc
  namespace: silverbullet
  labels:
    app.kubernetes.io/name: silverbullet
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi
  resources:
    requests:
      storage: 20Gi
