---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-secret
  namespace: kubevirt-manager
  labels:
    app: kubevirt-manager
    kubevirt-manager.io/version: 1.5.2
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: kubevirt_manager
        property: username
    - secretKey: password
      remoteRef:
        key: kubevirt_manager
        property: password


