---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://kubernetes-sigs.github.io/external-dns/

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-dns
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      version: 1.17.0
  interval: 30m
  maxHistory: 3
  install:
    crds: CreateReplace
    remediation:
      retries: 4
  releaseName: external-dns
  targetNamespace: networking
  values:
    image:
      tag: v0.18.0
    provider:
      name: pihole
    env:
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            key: pihole_password
            name: pihole-password
    extraArgs:
      - --pihole-server=http://10.3.3.11
      - --pihole-tls-skip-verify
    policy: upsert-only
    nodeSelector:
      node: "worker"
    
