---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app syncthing
  namespace: flux-system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: bjw-s
  maxHistory: 2
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  targetNamespace: storage
  values:
    controllers:
      syncthing:
        containers:
          app:
            image:
              repository: syncthing/syncthing
              tag: 1.29.4
            env:
              PUID: "1000"
              PGID: "1000"
            securityContext:
              # allowPrivilegeEscalation: false
              # readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 15m
                memory: 249Mi
              limits:
                memory: 512Mi

    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        # runAsNonRoot: true
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 65539
        seccompProfile:
          type: RuntimeDefault

    service:
      app:
        nameOverride: *app
        controller: *app
        ports:
          http:
            port: 8384

      listen:
        controller: *app
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.3.3.50
        ports:
          listen:
            enabled: true
            port: 22000
            protocol: TCP
            targetPort: 22000
          discovery:
            enabled: true
            port: 21027
            protocol: UDP
            targetPort: 21027
    ingress:
      app:
        className: tailscale
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: mdi-cloud
          gethomepage.dev/name: Sync
          gethomepage.dev/group: Applications
        path: /
        tls:
        - hosts:
          - dev-int-sync

    persistence:
      data:
        enabled: true
        type: sts
        #server: lochnas.chestr.dev
        #path: /volume1/shared/syncthing
        globalMounts:
          - path: /data

      # config:
      #   existingClaim: *app
      #   globalMounts:
      #     - path: /var/syncthing
