apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
spec:
  chart:
    spec:
      version: "2.27.0"
  values:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      enabled: true
      hosts:
      - production.pihole.fr3d.dev
      ingressClassName: cilium
      path: /
      pathType: Prefix
      tls:
      - hosts:
        - production.pihole.fr3d.dev
        secretName: pihole-tls
    persistentVolumeClaim:
      enabled: true
      storageClass: proxmox-data
      accessModes:
        - ReadWriteOnce
      size: 1024Mi
    mixedService: true
    podDnsConfig:
      enabled: true
      policy: "None"
