apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
spec:
  chart:
    spec:
      version: "2.27.0"
  values:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      enabled: true
      hosts:
      - production.internal.pihole.fr3d.dev
      ingressClassName: cilium
      path: /
      pathType: Prefix
      tls:
      - hosts:
        - production.internal.pihole.fr3d.dev
        secretName: pihole-tls
    persistentVolumeClaim:
      enabled: false
      storageClass: local-path
      accessModes:
        - ReadWriteOnce
      size: 4096Mi
    serviceDns:
      externalTrafficPolicy: Cluster
      mixedService: true
      LoadBalancerIP: 10.3.3.121
      annotations:
      type: LoadBalancer
    podDnsConfig:
      enabled: true
      policy: "None"
      nameservers:
        - 8.8.8.8
        - 1.1.1.1
    resources:
      limits:
        cpu: 400m
        memory: 200Mi
      requests:
        cpu: 400m
        memory: 200Mi
